name: build naive and push

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - buidldnaive
    # inputs:
    #   tags:
    #     description: 'The App version'
  push:
    tags: # 仅带 tag:v* 时构建
      - v*
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  APP_NAME: naive
  DOCKERHUB_REPO: ucatapp/naive

jobs:

  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          # builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64, linux/amd64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:latest
          #${{ env.DOCKERHUB_REPO }}:${{ github.event.inputs.tags }}
          # cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/naive:buildcache
          # cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/naive:buildcache,mode=max
    # - uses: actions/checkout@v3
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
